name: DVC Tracking with Github Actions
on: 
  pull_request
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      
      - name: Generate Report
        run: |
          echo "## Build Report 🚀" >> $GITHUB_STEP_SUMMARY
          echo "Status: Success" >> $GITHUB_STEP_SUMMARY
          echo "- Tally: 15 tests passed" >> $GITHUB_STEP_SUMMARY
          echo "- Coverage: 85%" >> $GITHUB_STEP_SUMMARY
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Running_updates
        env: 
          GH_TOKEN: ${{ github.token }}
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          make install 
          dvc repro
          # Configure Git
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
        
          # Generate the report
          echo "### 📊 Analysis for ${{ github.sha }}" > report.md
          dvc metrics diff >> report.md
          echo "### Region wise plot" >> report.md
          echo "![Region Plot](by_region.png)" >> report.md
        
          # Commit and Push the image (Fixes the "Detached HEAD" error)
          git add -f by_region.png report.md          
          git commit -m "chore: update plot [skip ci]" || echo "No changes"

          # 1. Pull the latest changes from the branch to sync up
          git pull origin ${{ github.head_ref }} --rebase
          git push origin HEAD:${{ github.head_ref }}       
          git fetch --prune
          ls -l
      - name: Post Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: report.md
        
          
